task: detection

num_classes: 80
remap_mscoco_category: True

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetectionCL

    img_folder: /workspace/coco/train2017/
    ann_file: /workspace/coco/annotations/instances_train2017.json

    transforms:
      type: Compose
      ops: ~

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetectionCL

    img_folder: /workspace/coco/val2017/
    ann_file: /workspace/coco/annotations/instances_val2017.json

    transforms:
      type: Compose
      ops: ~
