# CL General
start_task: 0
total_tasks: 2

# CL Strategy
pseudo_label: True
distill_attn: True
teacher_path: "/workspace/CL-RTDETR-DIFFUSION/outputs/weights/4040_t0_1e_ap0.35.pth"

# CL Rehearsal
rehearsal: False

# CL Eval
fpp: False

# WandB
wandb_name: "test4040"
