# CL General
start_task: 0
total_tasks: 2

# CL Strategy
pseudo_label: True
distill_attn: True
teacher_path: "/workspace/outputs/weights/7010_t0_35e_ap45.75.pth"

# CL Rehearsal
rehearsal: False

# CL Eval
fpp: False

# WandB
wandb_name: "7010_task1_fake_distill_20e"
